# Build Stage
FROM node:20 AS builder

WORKDIR /app

# 👉 Copy package files ก่อน เพื่อใช้ cache ของ npm install
COPY package.json ./
COPY package-lock.json ./   

# 👉 Run npm install แยกไว้ตรงนี้ (Docker cache ทำงานได้ดี)
RUN npm install

# 👉 Copy source code ทีหลัง
COPY . .

# 👉 Build Project
RUN npm run build -- --base=/sc3/

# Runtime Stage
FROM nginx:stable-alpine

RUN rm -rf /usr/share/nginx/html/

COPY --from=builder /app/dist /usr/share/nginx/html/

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
